attackinfo:
  ssh_hostname: 10.10.21.203
  ssh_username: ubuntu
  ssh_password: "010404"
  root_username: root
  root_password: "010404"
  attack_pattern: 2
  attack_target: T1574.006

pfinfo:
  target_agent: 2
  function_id: 2

  yunsuo_agent:
    ssh_hostname: 10.10.21.124
    ssh_username: root
    ssh_password: '010404'
    manage_center_ip: 10.10.21.119
    token: 495d75c06c564a0aa5d0755b9f00010c
    uuid: 154bbc80eac2a8a32e6c289227e3873e

  aliyun_agent:
     ssh_hostname: 10.10.21.106
     ssh_username: root
     ssh_password: '010404'
     accessKeyId: LTAI5tKzriqKJux8AWn72mDh
     accessKeySecret: DQDSg6t6IMih9MnGlykw0SYvGv20h9
     uuid: inet-ebb4b2df-384f-451d-a0be-9be0512bb8ae

  tencent_agent:
     ssh_hostname: 10.10.21.203
     ssh_username: root
     ssh_password: '010404'
     accessKeyId: AKIDqbGl9NyRkrwxpfNwEPO8jAQTL5iQG1b2
     accessKeySecret: MckjeP0QfhYCg2tX5RiKrCMN4iCZlolY
     uuid: ebb72142-e05d-e812-505e-05bf0d7b4907

malwareinfo:
  tencent_agent:
     ftp_hostname: 10.10.21.203
     ftp_username: ubuntu
     ftp_password: 010404
     folder_path: Malwares
     upload_path: /home/ubuntu/upload
     accessKeyId: AKIDqbGl9NyRkrwxpfNwEPO8jAQTL5iQG1b2
     accessKeySecret: MckjeP0QfhYCg2tX5RiKrCMN4iCZlolY
     uuid: ebb72142-e05d-e812-505e-05bf0d7b4907

  aliyun_agent:
    ftp_hostname: 10.10.21.106
    ftp_username: ubuntu
    ftp_password: 010404grz
    folder_path: Malwares
    upload_path: /home/ubuntu/upload
    accessKeyId: LTAI5tKzriqKJux8AWn72mDh
    accessKeySecret: DQDSg6t6IMih9MnGlykw0SYvGv20h9
    uuid: inet-ebb4b2df-384f-451d-a0be-9be0512bb8ae
